routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('/', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('login_auth');
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register')->name('register_auth');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

$this->get('forgot-password', 'Auth\RegisterController@forgot_password_form')->name('forgot_password_form');
$this->post('verify-user-forgot-pass', 'Auth\RegisterController@verify_user_forgot_password')->name('verify_user_forgot_password');


Route::prefix('portal')
->middleware('auth')
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('reset-password', 'UsersController@reset_password_form')->name('reset_password_form');
	Route::post('reset-password', 'UsersController@reset_password')->name('reset_password');

	#receipt
	Route::get('/official-receipt/{id?}', 'TransactionController@official_receipt')->name('official_receipt');

	Route::prefix('cust')
	->group(function(){
		Route::get('/', 'HomeController@cust')->name('cust');
		Route::get('/items/{id?}', 'CustomerController@index')->name('cust_items');
		Route::get('/transactions', 'CustomerController@transactions')->name('cust_transactions');
		#Route::get('/get-item', 'CustomerController@get_item')->name('user_get_item');

		Route::post('/add-to-cart', 'CustomerController@add_to_cart')->name('add_to_cart');

		Route::get('/confirmed-customer-details', 'CustomerController@confirm_customer_details')->name('confirm_customer_details');

		Route::get('/proceed-to-checkout', 'CustomerController@proceed_to_checkout')->name('proceed_to_checkout');
		Route::get('/remove-item-from-cart/{id?}', 'CustomerController@remove_item_from_cart')->name('remove_item_from_cart');
		
		Route::get('/confirmed-customer-details', 'CustomerController@confirm_customer_details')->name('confirm_customer_details');
		Route::post('/confirmed-checkout', 'CustomerController@confirmed_checkout')->name('confirmed_checkout');
		
		#success_order
		Route::get('/order-success/{id?}', 'CustomerController@order_success')->name('order_success');
		Route::get('/view-transaction/{id?}', 'CustomerController@view_transaction')->name('view_cust_transaction');

	});

	Route::prefix('admin')
	->middleware('AdminAccess')
	->group(function(){
		Route::get('/', 'HomeController@index')->name('home');
		Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('/categories', 'CategoryController@index')->name('categories');
		Route::get('/add-category', 'CategoryController@add_category')->name('add_category');
		Route::post('/submit-category', 'CategoryController@submit_category')->name('submit_category');
		Route::get('/edit-category/{id?}', 'CategoryController@edit_category')->name('edit_category');
		Route::get('/delete-category', 'CategoryController@delete_category')->name('delete_category');

		Route::get('/items', 'ItemController@index')->name('items');
		Route::post('/submit-item', 'ItemController@submit_item')->name('submit_item');
		Route::get('/add-item', 'ItemController@add_item')->name('add_item');
		Route::get('/edit-item/{id?}', 'ItemController@edit_item')->name('edit_item');
		Route::get('/delete-item', 'ItemController@delete_item')->name('delete_item');

		Route::get('/transactions','TransactionController@index')->name('transactions');
		Route::get('/view-transaction/{id?}','TransactionController@view_transaction')->name('view_transaction');

		Route::get('/accept-order/{id?}', 'TransactionController@accept_order')->name('accept_order');
		Route::get('/invalid-order/{id?}', 'TransactionController@invalid_order')->name('invalid_order');

		Route::resource('users', 'UsersController');
		Route::get('/disable-user', 'UsersController@disable_user')->name('disable_user');
		Route::get('generate-password', 'UsersController@generate_password')->name('generate_password');
	});
});

app/Transaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{
    public $table = 'transaction';
    public $fillable = ['cash_received',  'user_id', 'delivery_date'];
    public $timestamps = true;

     protected $dates = [
        'created_at', 'updated_at'
    ];


    public function user()
    {
        return $this->belongsTo('App\User');
    }
    
    public function transaction()
    {
        return $this->belongsTo('App\TransactionMenu');
    }

    public function transaction_reverse()
    {
        return $this->belongsTo('App\TransactionMenu', 'id');
    }

    public function transaction_user_details()
    {
        return $this->hasMany('App\TransacationUserDetails', 'transaction_id', 'id');
    }

     public function getTransactionNumberAttribute()
    {
        return str_pad($this->id, 10, '0', STR_PAD_LEFT);
    }
    
    public function getCurrentStatusAttribute()
    {
        switch($this->status)
        {
            case 1: return 'Pending';
            break;

            case 2:
              return 'Accepted';
            break;

            case 3:
              return 'Invalid';
            break;

        }
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Response;

use App\Items;
use App\User;
use App\Supplier;
use App\Category;
use App\SoftDeletes;


use App\Transaction;
use App\TransactionItem;
use App\TransactionUserDetails;

use \Carbon\Carbon;


class TransactionController extends Controller
{
    public function index()
    {
        $active_users = User::pluck('id');
    	$transactions = Transaction::whereIn('user_id', $active_users)->get();
    	$data = compact('transactions');
    	return view('transactions.index', $data);
    }

    public function view_transaction($transactionid)
    {
    	$transaction_user = Transaction::with('user')->where('id', $transactionid)->first();
    	$transaction_user_details = TransactionUserDetails::where('transaction_id', $transactionid)->first();
    	$transaction_user_items = TransactionItem::with(['item' => function ($q) {
                                      $q->withTrashed();
                                  }])->where('transaction_id', $transactionid)->get();
    	$data = compact('transactionid', 'transaction_user', 'transaction_user_details', 'transaction_user_items');
    	return view('transactions.view-transaction', $data);
    }

    public function accept_order($transactionid)
    {
    	$update_transaction = Transaction::find($transactionid);
    	$update_transaction->status = 2;
        $update_transaction->updated_at = Carbon::now();
    	$update_transaction->save();


        return redirect()->route('transactions')->with('success', 'Order has been accepted!');    
    }

    public function invalid_order($transactionid)
    {
    	$update_transaction = Transaction::find($transactionid);
    	$update_transaction->status = 3;
        $update_transaction->updated_at = Carbon::now();
    	$update_transaction->save();


        return redirect()->route('transactions')->with('success', 'Order has been invalidated!');    
    }

    public function official_receipt($transactionid)
    {
        $transaction = Transaction::with('user')->whereId($transactionid)->first();

        $transaction_items = TransactionItem::with(['item' => function ($q) {
                                      $q->withTrashed();
                                  }])->where('transaction_id', $transactionid)->get();

        $transaction_details = TransactionUserDetails::where('transaction_id', $transactionid)->first();

        $supplier = Supplier::whereId(1)->first();

        $data = compact('transactionid', 'transaction', 'transaction_items', 'transaction_details', 'supplier');

        return view('transactions.or', $data);
    }
}

resources/views/transactions/index.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="columns">
        <div class="column is-9">
            <h3 class="title is-3"><i class="fa fa-bars"></i>&nbsp;Transactions</h3>
        </div>
        <div class="column is-3">
        
        </div>
    </div>

     <table class="table is-bordered is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr> 
                <th width="10%" class="has-text-centered"></th>
                <th width="30%">Transaction No.</th>
                <th width="30%">Date of Transaction</th>
                <th width="20%">Delivery Date</th>
                <th width="10%">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $transaction)
            <tr>
                 <td class="has-text-centered">
                    <a href="{{ route('view_transaction', $transaction->id) }}" title="View transaction">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </a>
                </td>
                <td>{{ $transaction->transaction_number }}</td>
                <td>{{ $transaction->created_at }}</td>
                <td>{{ $transaction->delivery_date }}</td>
                <td>{{ $transaction->current_status }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="5" class="has-text-centered">No Transactions yet</td>
            </tr>
            @endforelse
        </tbody>
    </table>

@endsection

resources/views/transactions/or.blade.php
@extends('layouts.empty')

@section('content')
@parent
<style type="text/css">
body{
	font-size: 12px!important;
	overflow: hidden;
	width: 100%;
		margin: 0;
	padding: 0;
}
table th,
table td,
table tr{
	padding: 0!important;
	margin: 0!important;
	height: 0px!important;
}
table td{
	border: none!important;
}
table th{
	border-top: 1px solid rgba(0, 0, 0, 0.12);
	border-bottom: 1px solid rgba(0, 0, 0, 0.12);
}

</style>
<table class="table is-fullwidth is bordered" width="100%">
	<thead>
		<tr>
			<td style="text-align: center;" colspan="4"><strong style="font-size:15px;">KMart Official Receipt</strong></td>
		</tr>
		<tr>
			<td style="text-align: center;" colspan="4"><strong>{{ $supplier->address }}</strong></td>
		</tr>
		<tr>
			<td style="text-align: left;" colspan="1">O.R. No.</td>
			<td style="text-align: right;" colspan="3">{{ str_pad($transactionid, 10, '0', STR_PAD_LEFT) }}</td>
		</tr>
		<tr>
			<td style="text-align: left;" colspan="1">Transaction Date</td>
			<td style="text-align: right;" colspan="3">{{ $transaction->created_at }}</td>
		</tr>
		<tr>
			<td style="text-align: left;" colspan="1">Customer</td>
			<td style="text-align: right;" colspan="3">{{ $transaction->user->name }}</td>
		</tr>
		<tr>
			<td style="text-align: left;" colspan="1">Contact Number</td>
			<td style="text-align: right;" colspan="3">{{ $transaction_details->contact_number }}</td>
		</tr>
		<tr>
			<th style="text-align: left;" colspan="1">Item Name</th>
			<th style="text-align: right;" colspan="1">Quantity</th>
			<th style="text-align: right;" colspan="1">Price</th>
			<th style="text-align: right;" colspan="1">Total</th>
		</tr>
	</thead>
	<tbody>
		@php 
			$total=0; 
			$grandtotal=0;
		@endphp
		@foreach($transaction_items as $transaction_item)
		<tr>
			<td colspan="1" style="text-align: left;">{{ $transaction_item->item->first()->name }}</td>
			<td colspan="1" style="text-align: right;">{{ $transaction_item->quantity }}</td>
			<td colspan="1" style="text-align: right;">P {{ $transaction_item->price }}</td>
			<td colspan="1" style="text-align: right;">P {{ number_format($total =  $transaction_item->price * $transaction_item->quantity,2) }}</td>
		</tr>
		@php  
			$grandtotal = $total+$grandtotal;
		@endphp
		@endforeach
		<tr>
			<td id="grandtotal" colspan="3" style="text-align: right;">Total Bill :  </td>

			<td id="grandtotal" colspan="1" style="text-align: right;"><strong>P {{ number_format($grandtotal,2) }}</strong></td>
		</tr>
	</tbody>
</table>

<script type="text/javascript">
$(document).ready(function(){
	setTimeout(function(){ window.print(); 	}, 1000);
	setTimeout(function(){ close(); 		}, 2000);
});
</script>
@endsection

resources/views/transactions/view-transaction.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="columns">
        <div class="column is-9">
            <h3 class="title is-3"><i class="fa fa-bars"></i>&nbsp;Transaction No. {{ str_pad($transactionid, 10, '0', STR_PAD_LEFT) }}</h3>
        </div>
        <div class="column is-3 ">
            <a target="_blank" href="{{ route('official_receipt', $transactionid) }}" class="button is-info is-pulled-right">
                <i class="fa fa-print"></i> &nbsp;Print
            </a>
        </div>
    </div>
    <table class="table is-fullwidth">
        <thead>
            <tr>
                <th width="35%">Name</th>
                <th width="10%">Contact No.</th>
                <th width="55%">Address</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $transaction_user->user->name }}</td>
                <td>{{ $transaction_user->user->contact_number }}</td>
                <td>{{ $transaction_user_details->address }}</td>
            </tr>
            <tr>
                <td colspan="1"><strong> Has change for : </strong></td>
                <td colspan="4">P {{ $transaction_user->cash_received }}</td>
            </tr>
        </tbody>
    </table>
     <table class="table is-bordered is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr> 
                <th width="30%">Item</th>
                <th width="40%">Quantity</th>
                <th width="20%">Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transaction_user_items as $transaction_user_item)
            <tr>
                <td>{{ $transaction_user_item->item->first()->name }}</td>
                <td>{{ $transaction_user_item->quantity }}</td>
                <td>{{ $transaction_user_item->price }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <br>
    @if ($transaction_user->status == 1)
    <div class="field has-addons is-pulled-right">
        <div class="control">
            <a href="{{ route('accept_order', $transactionid) }}" class="button is-success ">Accept Order</a>  
        </div> &nbsp;
        <div class="control">
            <a href="{{ route('invalid_order', $transactionid) }}" class="button is-danger ">Invalid Order</a>  
        </div>
    </div>
    @endif
@endsection