routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('/', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('login_auth');
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@register')->name('register_auth');
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

$this->get('forgot-password', 'Auth\RegisterController@forgot_password_form')->name('forgot_password_form');
$this->post('verify-user-forgot-pass', 'Auth\RegisterController@verify_user_forgot_password')->name('verify_user_forgot_password');


Route::prefix('portal')
->middleware('auth')
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('reset-password', 'UsersController@reset_password_form')->name('reset_password_form');
	Route::post('reset-password', 'UsersController@reset_password')->name('reset_password');

	#receipt
	Route::get('/official-receipt/{id?}', 'TransactionController@official_receipt')->name('official_receipt');

	Route::prefix('cust')
	->group(function(){
		Route::get('/', 'HomeController@cust')->name('cust');
		Route::get('/items/{id?}', 'CustomerController@index')->name('cust_items');
		Route::get('/transactions', 'CustomerController@transactions')->name('cust_transactions');
		#Route::get('/get-item', 'CustomerController@get_item')->name('user_get_item');

		Route::post('/add-to-cart', 'CustomerController@add_to_cart')->name('add_to_cart');

		Route::get('/confirmed-customer-details', 'CustomerController@confirm_customer_details')->name('confirm_customer_details');

		Route::get('/proceed-to-checkout', 'CustomerController@proceed_to_checkout')->name('proceed_to_checkout');
		Route::get('/remove-item-from-cart/{id?}', 'CustomerController@remove_item_from_cart')->name('remove_item_from_cart');
		
		Route::get('/confirmed-customer-details', 'CustomerController@confirm_customer_details')->name('confirm_customer_details');
		Route::post('/confirmed-checkout', 'CustomerController@confirmed_checkout')->name('confirmed_checkout');
		
		#success_order
		Route::get('/order-success/{id?}', 'CustomerController@order_success')->name('order_success');
		Route::get('/view-transaction/{id?}', 'CustomerController@view_transaction')->name('view_cust_transaction');

	});

	Route::prefix('admin')
	->middleware('AdminAccess')
	->group(function(){
		Route::get('/', 'HomeController@index')->name('home');
		Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
		Route::get('/categories', 'CategoryController@index')->name('categories');
		Route::get('/add-category', 'CategoryController@add_category')->name('add_category');
		Route::post('/submit-category', 'CategoryController@submit_category')->name('submit_category');
		Route::get('/edit-category/{id?}', 'CategoryController@edit_category')->name('edit_category');
		Route::get('/delete-category', 'CategoryController@delete_category')->name('delete_category');

		Route::get('/items', 'ItemController@index')->name('items');
		Route::post('/submit-item', 'ItemController@submit_item')->name('submit_item');
		Route::get('/add-item', 'ItemController@add_item')->name('add_item');
		Route::get('/edit-item/{id?}', 'ItemController@edit_item')->name('edit_item');
		Route::get('/delete-item', 'ItemController@delete_item')->name('delete_item');

		Route::get('/transactions','TransactionController@index')->name('transactions');
		Route::get('/view-transaction/{id?}','TransactionController@view_transaction')->name('view_transaction');

		Route::get('/accept-order/{id?}', 'TransactionController@accept_order')->name('accept_order');
		Route::get('/invalid-order/{id?}', 'TransactionController@invalid_order')->name('invalid_order');

		Route::resource('users', 'UsersController');
		Route::get('/disable-user', 'UsersController@disable_user')->name('disable_user');
		Route::get('generate-password', 'UsersController@generate_password')->name('generate_password');
	});
});

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'name', 'email', 'password', 'address', 'contact_number', 'verified', 'role', 'created_at', 'updated_at'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

       protected $dates = [
        'deleted_at'
    ];

    public function getAccessStatusAttribute()
    {
    	if($this->role == 1)
    	{
    		return 'ADMIN';
    	}
    	return 'CUSTOMER';
    }

    public function verifyUser()
    {
        return $this->hasOne('App\VerifyUser');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\User;
use Auth;
use App\VerifyUser;
use App\Mail\VerifyMail;
use Mail;

class UsersController extends Controller
{
    public function index(Request $request)
    {
        $search = '';
        $query = new User;

        if($request->has('search'))
        {
            $search = $request->search;
            $query = $query->where('name', 'LIKE', "$search%")->orWhere('email', 'LIKE', "$search%");
        }

        $rows = $query->orderBy('name', 'ASC')->paginate(50);

        $data = compact('rows', 'search');

        return view('user.index', $data);
    }
    
    public function create()
    {
        $action = 'create';
        $route = route('users.store');
    	$name = old('name');
    	$email = old('email');
    	$access = old('access');

    	$data = compact('route', 'name', 'email', 'role', 'action');

        return view('user.create-form', $data);
    }
    
    public function store(Requests\UsersStoreRequest $request)
    {
        $input = $request->except('_token');
        $input['password'] = bcrypt('p@ssw0rd');

       $user = User::create($input);

        $verifyUser = VerifyUser::create([
            'user_id' => $user->id,
            'token' => str_random(40)
        ]);

        Mail::to($user->email)->send(new VerifyMail($user));
 
        
        return redirect()->route('users.create')->with('success', 'User Successfully added!');
    }
        
    public function disable_user(Request $request)
    {
        $mail_q = User::whereId($request->userid)->pluck('email');
        $mail = "deleted".$mail_q;
        $update_email = User::find($request->userid);
        $update_email->email = $mail;
        $update_email->save();

        $user = User::find($request->userid);
        $user->delete();
    }


    public function edit($id)
    {
        $action = 'edit';
    	$route = route('users.update', $id);
        $row = User::whereId($id)->first();
    	$name = $row->name;
    	$email = $row->email;
    	$access = $row->role;

    	$data = compact('route', 'name', 'email', 'role', 'action', 'id');

        return view('user.create-form', $data);
    }
    
    public function update($id, Requests\UsersUpdateRequest $request)
    {
        #dd($request->all());   
        $input = $request->except('_token', '_method', 'password');

        User::whereId($id)->update($input);

        return redirect()->route('users.edit', $id)->with('success', 'User Successfully updated!');
    }
    
    public function show($id)
    {
        $row = User::whereId($id)->first();
        $name = $row->name;
        $email = $row->email;
        $access = $row->access;
        $active = $row->active;

        $data = compact('name', 'email', 'access', 'active');

        return view('user.show', $data);
    }

    public function generate_password(Request $request)
    {
        $password = str_random(10);

        User::whereId($request->id)->update([ 'password'=>bcrypt($password) ]);

        return response()->json([ 'password'=>$password ]);
    }

    public function reset_password_form()
    {
        $route = route('reset_password');

        if(Auth::user()->role == 2)
        {
            $extends = 'layouts.cust';
        }else{
            $extends = 'layouts.master';
        }

        $data = compact('route', 'extends');

        return view('user.reset', $data);
    }

    public function reset_password(Request $request)
    {
        $request->validate([
            'password' => 'required',
            'confirm_password' => 'required|same:password'
        ]);

        $password = bcrypt($request->password);

        User::whereId(Auth::user()->id)->update([ 'password'=>$password ]);

        return redirect()->route('reset_password_form')->with('success', 'Password Successfully changed!');
    }
}

resources/views/user/create-form.blade.php
@extends('layouts.master')
@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ route('users.index') }}">User</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Form</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            @include('layouts.validation-messages')
            <div class="content">
                <form action="{{ $route }}" method="post">

                    <div class="columns">
                        <div class="column is-7">

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="name">Name</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="text" name="name" id="name" value="{{ $name }}">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="email">E-Mail</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="email" name="email" id="email" value="{{ $email }}">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="role">Role</label>
                                </div>
                                <div class="field-body">
                                    <div class="field is-narrow">
                                        <div class="control">
                                            <div class="select is-fullwidth">
                                                <select name="role" id="role">
                                                    <option value="1">Admin</option>
                                                    <option value="2">Customer</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            @if($action == 'edit')
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="name">Password</label>
                                </div>
                                <div class="field-body">
                                    <div class="field has-addons">
                                        <div class="control">
                                        </div>
                                        <div class="control">
                                            <input class="input is-normal" type="text" name="password" id="password" value="" readonly="">
                                        </div>
                                        <div class="control">
                                            <a href="javascript:void(0)" onclick="generate_password({{ $id }})" class="button is-dark"><i class="fa fa-refresh"></i>&nbsp;&nbsp;Generate</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {{ method_field('PUT') }}
                            @endif

                            <div class="field is-horizontal">
                                <div class="field-label"></div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="control">
                                            <button class="button is-info is-normal">Submit</button>                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {!! csrf_field() !!}
                </form>
            </div>
        </div>
    </div>
@endsection
<input type="hidden" id="generate_password" value="{{ route('generate_password') }}">
<script src="{{ asset('js/jquery.js') }}"></script>
<script type="text/javascript">
    var xhr_generate_password = null;

    $('#role option[value={{ $role or 0 }}]').attr('selected','selected');

    function generate_password(id)
    {
        xhr_generate_password = $.ajax({
            type : 'get',
            url : $("#generate_password").val(),
            data : 'id=' + id,
            dataType : "json",
            beforeSend: function(xhr) 
            {
                if (xhr_generate_password != null)
                {
                    xhr_generate_password.abort();
                }
            }
        }).done(function(data) 
        {
            $('#password').val(data['password']);
        }).fail(function(jqXHR, textStatus) 
        {
            //console.log('Request failed: ' + textStatus);
        });
    }
</script>

resources/views/user/index.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="columns">
        <div class="column is-9">
            <h3 class="title is-3"><i class="fa fa-users"></i> Users</h3>
        </div>
        <div class="column is-3">
            <form action="" method="get">
                <div class="field has-addons">
                    <div class="control">
                        <a class="button is-static"><i class="fa fa-search"></i></a>
                    </div>
                    <div class="control">
                        <input class="input is-normal" type="text" name="search" id="search" value="{{ $search }}">
                    </div>
                    <div class="control">
                        <button class="button is-dark">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <table class="table is-bordered is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr>
                <th width="5%" class="has-text-centered"><a href="{{ route('users.create') }}"><i class="fa fa-plus-circle fa-lg"></i></a></th>
                <td width="35%">Name</td>
                <td width="20%">Email</td>
                <td width="10%">Access</td>
                <td width="15%">Created At</td>
                <td width="15%">Updated At</td>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
            <tr id="user-row-{{ $row->id }}">
                <td class="has-text-centered">
                    @if(Auth::user()->access == 0)
                    <a href="{{ route('users.edit', $row->id) }}" title="Edit User Details">
                        <i class="fa fa-edit"></i>
                    </a>
                     <a onclick="RemoveUser({{ $row->id }})" id="delete_user{{ $row->id }}" title="Disable User">
                        <i class="fa fa-ban" aria-hidden="true"></i>
                    </a>
                    @else
                        &nbsp;
                    @endif
                 <!--    <a href="{{ route('users.show', $row->id) }}" title="Show User Details">
                        <i class="fa fa-list-alt"></i>
                    </a> -->
                </td>
                <td>{{ $row->name }}</td>
                <td>{{ $row->email }}</td>
                <td>{{ $row->access_status }}</td>
                <td>{{ $row->created_at }}</td>
                <td>{{ $row->updated_at }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {!! $rows->appends(['search'=>$search])->links('vendor.pagination.default') !!}
        
<script type="text/javascript">
    function RemoveUser(userid, selector)
    {
        if(confirm("Are you sure to disable this user?") ==  true){
            $.ajax({
                type : 'GET',
                url : '{{ route("disable_user") }}',
                data : 'userid='+userid,
                cache : false,
                dataType : "script"
            }).done(function(response) {
                $(selector).closest("tr").remove();
                $('#user-row-'+userid).remove();
            }).fail(function(jqXHR, textStatus, y) {    
                //alert(textStatus);
            });
        }
    }
</script>
@endsection

resources/views/user/reset.blade.php
@extends($extends)

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li class="is-active"><a href="#" aria-current="page">Reset Password</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            @include('layouts.validation-messages')
            <div class="content">
                <form action="{{ $route }}" method="post">

                    <div class="columns">
                        <div class="column is-10">

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="password">Password</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="password" name="password" id="password" value="">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="confirm_password">Confirm Password</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="password" name="confirm_password" id="confirm_password" value="">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label"></div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="control">
                                            <button class="button is-info is-normal">Submit</button>
                                            {!! csrf_field() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ route('users.index') }}">User</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Details</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            <div class="content">

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" >Name</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                {{ $name }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="email">E-Mail</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                {{ $email }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="access">Access</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-narrow">
                            <div class="control">
                                {{ $access }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="access">Active</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-narrow">
                            <div class="control">
                                {{ $access }}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection